"""allow placeholder stocks and nullable watchlist_id on change_events

Revision ID: 47cacc8e4095
Revises: 04cfacfdb65b
Create Date: 2026-09-04 22:28:38.577074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cacc8e4095'
down_revision: Union[str, None] = '04cfacfdb65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_events', 'watchlist_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('change_events_watchlist_id_fkey'), 'change_events', type_='foreignkey')
    op.create_foreign_key(
        'change_events_watchlist_id_fkey',
        'change_events',
        'watchlists',
        ['watchlist_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.alter_column('stocks', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('stocks', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('stocks', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('change_events_watchlist_id_fkey', 'change_events', type_='foreignkey')
    op.create_foreign_key(
        op.f('change_events_watchlist_id_fkey'),
        'change_events',
        'watchlists',
        ['watchlist_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.alter_column('change_events', 'watchlist_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
