"""initial schema

Revision ID: ef67654ba6f2
Revises: 
Create Date: 2026-09-04 21:12:18.495408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ef67654ba6f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('market_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('EARNINGS', 'DIVIDEND', 'SPLIT', 'GUIDANCE', 'ANALYST_UPDATE', name='market_event_type'), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_events_stock_id_event_date', 'market_events', ['stock_id', 'event_date'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('average_volume', sa.BigInteger(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_stock_id_timestamp', 'market_snapshots', ['stock_id', 'timestamp'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'url', name='uq_news_events_stock_id_url')
    )
    op.create_index('ix_news_events_stock_id_published_at', 'news_events', ['stock_id', 'published_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('price_change_threshold', sa.Numeric(precision=5, scale=2), server_default='5.00', nullable=False),
    sa.Column('volume_spike_threshold', sa.Numeric(precision=5, scale=2), server_default='100.00', nullable=False),
    sa.Column('earnings_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('news_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_stock_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('last_seen_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_seen_volume', sa.BigInteger(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_id', name='uq_user_stock_states_user_id_stock_id')
    )
    op.create_index('ix_user_stock_states_stock_id', 'user_stock_states', ['stock_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlists_user_id_name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PRICE_CHANGE', 'VOLUME_SPIKE', 'NEWS', 'EARNINGS', 'DIVIDEND', 'SPLIT', 'GUIDANCE', 'ANALYST_UPDATE', 'OTHER', name='change_event_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='change_event_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_events_unacknowledged', 'change_events', ['user_id', 'acknowledged_at'], unique=False, postgresql_where=sa.text('acknowledged_at IS NULL'))
    op.create_index('ix_change_events_user_id_detected_at', 'change_events', ['user_id', 'detected_at'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'stock_id', name='uq_watchlist_items_watchlist_id_stock_id')
    )
    op.create_index('ix_watchlist_items_stock_id', 'watchlist_items', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_items_stock_id', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('ix_change_events_user_id_detected_at', table_name='change_events')
    op.drop_index('ix_change_events_unacknowledged', table_name='change_events', postgresql_where=sa.text('acknowledged_at IS NULL'))
    op.drop_table('change_events')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_user_stock_states_stock_id', table_name='user_stock_states')
    op.drop_table('user_stock_states')
    op.drop_table('user_preferences')
    op.drop_index('ix_news_events_stock_id_published_at', table_name='news_events')
    op.drop_table('news_events')
    op.drop_index('ix_market_snapshots_stock_id_timestamp', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_market_events_stock_id_event_date', table_name='market_events')
    op.drop_table('market_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###

    # native Postgres ENUM types are not dropped automatically when their
    # columns/tables are dropped, so remove them explicitly here.
    postgresql.ENUM(name='change_event_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='change_event_severity').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='market_event_type').drop(op.get_bind(), checkfirst=True)
